### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by zlx** [zlx/API-mock-server#1]
## v1.0
- [x] 1. setup mock server work
- [x] 2. setup database and save config into database
- [x] 3. setup active_admin and add config page
- [x] 3 change to sinatra module
- [x] 4. add support for params
- [x] 5. add create new API interface
- [x] 6 make new route work need not restart server
- [x] 7 add more effect and validates for create API
- [x] 8. Add great show for Response
- [x] 9. API can modify
- [x] 10. can destroy API
- [x] 11. default namespace (mock) for mock server
- [x] 12. can deploy on server(tag 1.0)

---
## v1.2
- [x] 13. Make route update without restart
- [x] 15. Add Test cover the main function
- [x] 16. Integration Code Editor for response
- [x] 17. Add authentication module
- [x] 18. Add Support for multiple same route(same verb and same url)
- [x] 19. Add function to make route active and inactive
- [x] 20. Add \* Support for show page(eg: /users/1, /users/2)

---
## v1.2.1
- [x] 1. Add code live reload
- [x] 2. Add route category support
- [x] 3. use ace as json editor and validator

---
- [x] Add API Document page (example: http://docs.v5.apiary.io/)
- [ ] Support multiple buckets
- [ ] Add API document export support
- [ ] Add API Test advice support
- [ ] Add params validates(presence, type) support
- [ ] Add authenication support for created api
- [ ] Add header support
- [ ] Add production configuration
- [ ]  can import API at once
